### ISSUE TITLE
examples/mifareclassic_ndeftoclassic.py reports "TypeError" in Line 111 and 128

### ISSUE THREAD

**Issue by tloehr** [gassajor000/pn532pi#13]
This is only a minor -side- issue, but could confuse the user.

Had to fix both lines like this:

``` python
blockBuffer = bytearray('\x00' * 16, encoding="utf-8")
```

You may want to fix it in the source.

Occured on Raspbian 1:6.1.63-1+rpt1 (2023-11-24) armv6l GNU/Linux
Python 3.11.2

**Comment by gassajor000** [comment]
Good catch, will fix in the next patch.

**Comment by gassajor000** [comment]
Good catch, will fix in the next patch.
