### ISSUE TITLE
[BUG] - Allow adjusting SPI bus speed to fix buggy pn532 modules

### ISSUE THREAD

**Issue by ebradbury** [gassajor000/pn532pi#17]
### What happened?

Many people appear to be struggling to get the pn532 module to work over SPI (myself included). I'm using the elechous pn532 v3 with a rpi 5. I was only able to get it to work by decreasing the SPI bus speed in a rather hacky way.

The solution for me was adding `nfc._interface._spi.max_speed_hz = 100000` after `nfc.begin()`. Otherwise the device would never connect.

Hope that helps someone. Maybe we can make 100kz the default speed or provide an option to adjust the speed in the constructor?

### Reproducibility

Always (100% of runs)

### Steps to Reproduce

1. Connect elechous pn532 v3 module to rpi 5 SPI
2. Run SPI example
3. See that device is not detected

### Code to reproduce

```Python
# Use examples/iso14443a_uid.py
```

### Host Controller

Raspberry Pi 5

### Python Version

3.11.2

### Interface Mode

SPI

### Power Supply

Pi 3.3v or 5v

**Comment by gassajor000** [comment]
Yes that does seem to be an oversight in the original arduino library. I'll can push a patch to specify a bus speed. 100 KHz seems like a pretty significant speed reduction though. Have you tried anything between 1 and 5 MHz?

**Comment by gassajor000** [comment]
Haven't heard anything back so I am just going to lower the default speed to 4 MHz.

**Comment by ebradbury** [comment]
Thanks for adjusting this!
